-- SmartHostel Database Schema for MySQL 8.0.19
-- Create Database
CREATE DATABASE IF NOT EXISTS smarthostel;
USE smarthostel;

-- Drop tables if exist (in reverse order of dependencies)
DROP TABLE IF EXISTS ROOMASSIGNEDTO;
DROP TABLE IF EXISTS STUDENTPHONENO;
DROP TABLE IF EXISTS MEALMENU;
DROP TABLE IF EXISTS CHOICE;
DROP TABLE IF EXISTS ATTENDANCE;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS HOSTELS;

-- Create HOSTELS table
CREATE TABLE HOSTELS (
    HostelNo VARCHAR(10) PRIMARY KEY,
    HostelName VARCHAR(100) NOT NULL,
    TotalRooms INT,
    TotalFloors INT,
    Type ENUM('BOYS', 'GIRLS') NOT NULL
);

-- Create ROOM table
CREATE TABLE ROOM (
    RoomNo VARCHAR(20) PRIMARY KEY,
    Capacity INT NOT NULL DEFAULT 2,
    HostelNo VARCHAR(10) NOT NULL,
    Floor INT,
    FOREIGN KEY (HostelNo) REFERENCES HOSTELS(HostelNo) ON DELETE CASCADE
);

-- Create STUDENT table
CREATE TABLE STUDENT (
    StudentID VARCHAR(20) PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    MiddleName VARCHAR(50),
    LastName VARCHAR(50) NOT NULL,
    RoomNo VARCHAR(20),
    HostelNo VARCHAR(10),
    FOREIGN KEY (RoomNo) REFERENCES ROOM(RoomNo) ON DELETE SET NULL,
    FOREIGN KEY (HostelNo) REFERENCES HOSTELS(HostelNo) ON DELETE SET NULL
);

-- Create EMPLOYEES table
CREATE TABLE EMPLOYEES (
    SSN VARCHAR(20) PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    MiddleName VARCHAR(50),
    LastName VARCHAR(50) NOT NULL,
    Role ENUM('ADMIN', 'WARDEN', 'MESS_STAFF', 'SECURITY') NOT NULL
);

-- Create USERS table (for authentication)
CREATE TABLE USERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role ENUM('STUDENT', 'ADMIN', 'MESS_STAFF') NOT NULL,
    room_number VARCHAR(20),
    student_id VARCHAR(20),
    employee_ssn VARCHAR(20),
    FOREIGN KEY (student_id) REFERENCES STUDENT(StudentID) ON DELETE SET NULL,
    FOREIGN KEY (employee_ssn) REFERENCES EMPLOYEES(SSN) ON DELETE SET NULL
);

-- Create ATTENDANCE table
CREATE TABLE ATTENDANCE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    StudentID VARCHAR(20) NOT NULL,
    TimeStamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Type ENUM('IN', 'OUT') NOT NULL,
    EmployeeSSN VARCHAR(20),
    Location VARCHAR(100),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID) ON DELETE CASCADE,
    FOREIGN KEY (EmployeeSSN) REFERENCES EMPLOYEES(SSN) ON DELETE SET NULL
);

-- Create CHOICE table (meal opt-outs)
CREATE TABLE CHOICE (
    OptID BIGINT AUTO_INCREMENT PRIMARY KEY,
    Date DATE NOT NULL,
    MealTime ENUM('BREAKFAST', 'LUNCH', 'DINNER') NOT NULL,
    StudentID VARCHAR(20) NOT NULL,
    OptedOut BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID) ON DELETE CASCADE,
    UNIQUE KEY unique_meal_choice (StudentID, Date, MealTime)
);

-- Create MEALMENU table
CREATE TABLE MEALMENU (
    PoolID BIGINT AUTO_INCREMENT PRIMARY KEY,
    Day ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY') NOT NULL,
    MealTime ENUM('BREAKFAST', 'LUNCH', 'DINNER') NOT NULL,
    MenuItem VARCHAR(255) NOT NULL,
    Category VARCHAR(50)
);

-- Create ROOMASSIGNEDTO table
CREATE TABLE ROOMASSIGNEDTO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    RoomNo VARCHAR(20) NOT NULL,
    StudentID VARCHAR(20) NOT NULL,
    AssignedDate DATE,
    IsActive BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (RoomNo) REFERENCES ROOM(RoomNo) ON DELETE CASCADE,
    FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID) ON DELETE CASCADE
);

-- Create STUDENTPHONENO table
CREATE TABLE STUDENTPHONENO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    StudentID VARCHAR(20) NOT NULL,
    PhoneNo VARCHAR(15) NOT NULL,
    IsPrimary BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID) ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX idx_attendance_student ON ATTENDANCE(StudentID);
CREATE INDEX idx_attendance_timestamp ON ATTENDANCE(TimeStamp);
CREATE INDEX idx_attendance_type ON ATTENDANCE(Type);
CREATE INDEX idx_choice_date ON CHOICE(Date);
CREATE INDEX idx_choice_mealtime ON CHOICE(MealTime);
CREATE INDEX idx_student_hostel ON STUDENT(HostelNo);
CREATE INDEX idx_room_hostel ON ROOM(HostelNo);
